set shell := ["bash", "-c"]

init:
    python3 -m venv venv && \
    source ./venv/bin/activate && \
    pip install poetry && \
    poetry install

source:
    source ./venv/bin/activate

run target:
    source ./venv/bin/activate && \
    python3 gauss_task{{target}}.py

run-go:
    go run golang_implementation/main.go

run-custom:
    source ./venv/bin/activate && \
    python3 gauss_task_custom.py
