set shell := ["bash", "-c"]

init:
    python3 -m venv venv && \
    source ./venv/bin/activate && \
    pip install poetry && \
    poetry install

source:
    source ./venv/bin/activate

run target:
    source ./venv/bin/activate && \
    python3 open_cv_task{{target}}.py
